
drop function if exists public.create_profile(text, text) cascade;
drop function if exists public.set_pseudo(text) cascade;
drop function if exists public.set_cg_username(text) cascade;
drop function if exists public.equip_skin(text) cascade;
drop function if exists public.equip_weapon(text) cascade;
drop function if exists public.buy_skin(text) cascade;
drop function if exists public.mark_item_seen(text, text) cascade;
drop function if exists public.set_accessories(text[]) cascade;
drop function if exists public.report_result(boolean, boolean, integer) cascade;
drop function if exists public.report_result(boolean, boolean, integer, uuid) cascade;
drop function if exists public.record_stats(integer, integer, integer, boolean) cascade;
drop function if exists public.hn_period_key(text) cascade;
drop function if exists public.challenge_defs(text, text) cascade;
drop function if exists public.bump_challenge(text, integer) cascade;
drop function if exists public.challenge_state() cascade;
drop function if exists public.claim_challenge(text, integer) cascade;
drop function if exists public.spin_wheel() cascade;
drop function if exists public.send_friend_request(text) cascade;
drop function if exists public.respond_friend_request(uuid, boolean) cascade;
drop function if exists public.remove_friend(uuid) cascade;
drop function if exists public.list_friends() cascade;
drop function if exists public.reward_ad() cascade;
drop function if exists public.ad_case() cascade;
drop function if exists public.ad_item_needed(text, text) cascade;
drop function if exists public.ad_owns_item(uuid, text, text) cascade;
drop function if exists public.ad_watch_item(text, text) cascade;
drop function if exists public.ad_state() cascade;
drop function if exists public.current_season() cascade;
drop function if exists public.season_days_left() cascade;
drop function if exists public.ensure_season(uuid) cascade;
drop function if exists public.grant_xp(uuid, integer) cascade;
drop function if exists public.ensure_friend_code(uuid) cascade;
drop function if exists public.season_info() cascade;
drop function if exists public.leaderboard_top() cascade;
drop function if exists public.pass_reward(integer, integer) cascade;
drop function if exists public.pass_state() cascade;
drop function if exists public.claim_pass_level(integer) cascade;
drop function if exists public.minigame_xp(text, integer) cascade;
drop function if exists public.story_xp(integer) cascade;
drop function if exists public.story_reward() cascade;
drop function if exists public.bump_event(text, integer) cascade;
drop function if exists public.bump_playtime(integer) cascade;
drop function if exists public.event_state() cascade;
drop function if exists public.event_claim(text) cascade;
drop function if exists public.item_rarity(text, text) cascade;
drop function if exists public.item_refund(text, text) cascade;
drop function if exists public.admin_set_ban(uuid, boolean, text) cascade;
drop function if exists public.admin_stats() cascade;
drop function if exists public.admin_search_players(text, integer, integer) cascade;
drop function if exists public.admin_delete_event(text) cascade;
drop function if exists public.admin_end_event(text) cascade;
drop function if exists public.admin_upsert_event(text, text, text, integer, text, text, integer, integer, text) cascade;
drop function if exists public.admin_list_events() cascade;
drop function if exists public.admin_list_banned() cascade;
drop function if exists public.assert_admin() cascade;

drop table if exists public.admins cascade;
drop table if exists public.event_progress cascade;
drop table if exists public.events cascade;
drop table if exists public.ad_unlocks cascade;
drop table if exists public.pass_claims cascade;
drop table if exists public.season_badges cascade;
drop table if exists public.season_history cascade;
drop table if exists public.challenge_progress cascade;
drop table if exists public.friendships cascade;
drop table if exists public.profile_weapons cascade;
drop table if exists public.profile_accessories cascade;
drop table if exists public.profile_skins cascade;
drop table if exists public.weapons cascade;
drop table if exists public.accessories cascade;
drop table if exists public.skins cascade;
drop table if exists public.app_meta cascade;
drop table if exists public.profiles cascade;

delete from auth.users;
